version: 2

archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
    ldflags:
      - -s -w -X github.com/YakDriver/tfproviderdocs/version.Version={{.Version}} -X github.com/YakDriver/tfproviderdocs/version.VersionPrerelease=
    main: .

dockers:
  - build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
    image_templates:
      - "moab4x/tfproviderdocs:{{ .Version }}"
      - "moab4x/tfproviderdocs:{{ .Major }}.{{ .Minor }}"
      - "moab4x/tfproviderdocs:latest"

milestones:
  - close: true
  - fail_on_error: false

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
