version: 2

archives:
  - format_overrides:
      - goos: windows
        format: zip

before:
  hooks:
    - go mod download

brews:
  - dependencies:
      - go
    description: Terraform Provider Documentation Tool
    directory: Formula
    repository:
      owner: YakDriver
      name: homebrew-tap
    homepage: https://github.com/YakDriver/tfproviderdocs
    install: |
      bin.install "tfproviderdocs"
    test: |
      system "#{bin}/tfproviderdocs -v"
    commit_author:
      name: yakdriverbot
      email: f1formula.juan@gmail.com

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
    ldflags:
      - -s -w -X github.com/YakDriver/tfproviderdocs/version.Version={{.Version}} -X github.com/YakDriver/tfproviderdocs/version.VersionPrerelease=
    main: .

dockers:
  - build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
    image_templates:
      - "moab4x/tfproviderdocs:{{ .Version }}"
      - "moab4x/tfproviderdocs:{{ .Major }}.{{ .Minor }}"
      - "moab4x/tfproviderdocs:latest"

milestones:
  - close: true

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
